### ISSUE TITLE
Menu Bug

### ISSUE THREAD

**Issue by arsedgie** [squidypal/HBMF--Hard-Bullet-modding-framework-#2]
I'm using steam VR with the Oculus Quest 2. Whenever I load my mods and get into game, pressing the left joystick button immediately crashes the game. The Melon loader console also says how the button has been remapped for HBMF. How can I fix this?

**Comment by notnotnotswipez** [comment]
Smh

**Comment by notnotnotswipez** [comment]
Uninstall the sex mod

**Comment by arsedgie** [comment]
i just thought it was interesting lmao
